// Code generated by Slice Machine. DO NOT EDIT.

import BigText from './BigText';
import Hero from './Hero';

export {
	BigText,
	Hero,
};

export const components = {
	big_text: BigText,
	hero: Hero,
};
